kind: Service
apiVersion: v1
metadata:
  name: todoapp-test-${TARGET_ROLE}
  labels:
    app: todoapp
    role: test-${TARGET_ROLE}
spec:
  type: LoadBalancer
  selector:
    app: todoapp
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 8080
